Load Required Libraries

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import sklearn
import sqlalchemy
import tensorflow as tf
import psycopg


from sqlalchemy import create_engine, text
from getpass import getpass

from pathlib import Path

In [14]:
%pip install pandas numpy matplotlib seaborn scikit-learn sqlalchemy "psycopg[binary]" jupyter

Requirement already satisfied: pandas in c:\Users\Ranjana\miniconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: numpy in c:\Users\Ranjana\miniconda3\Lib\site-packages (2.4.6)
Requirement already satisfied: matplotlib in c:\Users\Ranjana\miniconda3\Lib\site-packages (3.11.0)
Requirement already satisfied: seaborn in c:\Users\Ranjana\miniconda3\Lib\site-packages (0.13.2)
Requirement already satisfied: scikit-learn in c:\Users\Ranjana\miniconda3\Lib\site-packages (1.9.0)
Requirement already satisfied: sqlalchemy in c:\Users\Ranjana\miniconda3\Lib\site-packages (2.1.4)
Collecting jupyter
  Downloading jupyter-1.1.1-py2.py3-none-any.whl.metadata (2.0 kB)
Collecting psycopg[binary]
  Downloading psycopg-3.3.6-py3-none-any.whl.metadata (4.4 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Ranjana\miniconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from matplotlib) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from matplotlib) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=9 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from matplotlib) (12.2.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.10.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from scikit-learn) (1.18.0)
Requirement already satisfied: joblib>=1.4.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: narwhals>=2.0.1 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from scikit-learn) (2.22.1)
Requirement already satisfied: threadpoolctl>=3.5.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from sqlalchemy) (4.15.0)
Collecting psycopg-binary==3.3.6 (from psycopg[binary])
  Downloading psycopg_binary-3.3.6-cp313-cp313-win_amd64.whl.metadata (2.8 kB)
Requirement already satisfied: notebook in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyter) (7.6.0)
Collecting jupyter-console (from jupyter)
  Downloading jupyter_console-6.6.3-py3-none-any.whl.metadata (5.8 kB)
Requirement already satisfied: nbconvert in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyter) (7.17.1)
Requirement already satisfied: ipykernel in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyter) (7.3.0)
Requirement already satisfied: ipywidgets in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyter) (8.1.9)
Requirement already satisfied: jupyterlab in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyter) (4.6.0)
Requirement already satisfied: six>=1.5 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: comm>=0.1.1 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from ipykernel->jupyter) (0.2.3)
Requirement already satisfied: debugpy>=1.6.5 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from ipykernel->jupyter) (1.8.21)
Requirement already satisfied: ipython>=7.23.1 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from ipykernel->jupyter) (9.14.1)
Requirement already satisfied: jupyter-client>=8.9.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from ipykernel->jupyter) (8.9.1)
Requirement already satisfied: jupyter-core!=6.0.*,>=5.1 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from ipykernel->jupyter) (5.9.1)
Requirement already satisfied: matplotlib-inline>=0.1 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from ipykernel->jupyter) (0.2.2)
Requirement already satisfied: nest-asyncio2>=1.7.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from ipykernel->jupyter) (1.7.2)
Requirement already satisfied: psutil>=5.7 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from ipykernel->jupyter) (7.2.2)
Requirement already satisfied: pyzmq>=25 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from ipykernel->jupyter) (27.1.0)
Requirement already satisfied: tornado>=6.4.1 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from ipykernel->jupyter) (6.5.7)
Requirement already satisfied: traitlets>=5.4.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from ipykernel->jupyter) (5.15.1)
Requirement already satisfied: colorama>=0.4.4 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.4.6)
Requirement already satisfied: decorator>=5.1.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (5.3.1)
Requirement already satisfied: ipython-pygments-lexers>=1.0.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (1.1.1)
Requirement already satisfied: jedi>=0.18.2 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.20.0)
Requirement already satisfied: prompt_toolkit<3.1.0,>=3.0.41 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (3.0.52)
Requirement already satisfied: pygments>=2.14.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (2.20.0)
Requirement already satisfied: stack_data>=0.6.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from ipython>=7.23.1->ipykernel->jupyter) (0.6.3)
Requirement already satisfied: wcwidth in c:\Users\Ranjana\miniconda3\Lib\site-packages (from prompt_toolkit<3.1.0,>=3.0.41->ipython>=7.23.1->ipykernel->jupyter) (0.8.1)
Requirement already satisfied: parso<0.9.0,>=0.8.6 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jedi>=0.18.2->ipython>=7.23.1->ipykernel->jupyter) (0.8.7)
Requirement already satisfied: platformdirs>=2.5 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyter-core!=6.0.*,>=5.1->ipykernel->jupyter) (4.9.4)
Requirement already satisfied: executing>=1.2.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (2.2.1)
Requirement already satisfied: asttokens>=2.1.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (3.0.1)
Requirement already satisfied: pure-eval in c:\Users\Ranjana\miniconda3\Lib\site-packages (from stack_data>=0.6.0->ipython>=7.23.1->ipykernel->jupyter) (0.2.3)
Requirement already satisfied: widgetsnbextension~=4.0.16 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from ipywidgets->jupyter) (4.0.16)
Requirement already satisfied: jupyterlab_widgets~=3.0.17 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from ipywidgets->jupyter) (3.0.17)
Requirement already satisfied: async-lru>=1.0.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyterlab->jupyter) (2.3.0)
Requirement already satisfied: httpx<1,>=0.25.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyterlab->jupyter) (0.28.1)
Requirement already satisfied: jinja2>=3.0.3 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyterlab->jupyter) (3.1.6)
Requirement already satisfied: jupyter-builder>=1.0.2 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyterlab->jupyter) (1.0.2)
Requirement already satisfied: jupyter-lsp>=2.0.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyterlab->jupyter) (2.3.1)
Requirement already satisfied: jupyter-server<3,>=2.19.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyterlab->jupyter) (2.20.0)
Requirement already satisfied: jupyterlab-server<3,>=2.28.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyterlab->jupyter) (2.28.0)
Requirement already satisfied: notebook-shim>=0.2 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyterlab->jupyter) (0.2.4)
Requirement already satisfied: anyio in c:\Users\Ranjana\miniconda3\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (4.12.1)
Requirement already satisfied: certifi in c:\Users\Ranjana\miniconda3\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (2026.4.22)
Requirement already satisfied: httpcore==1.* in c:\Users\Ranjana\miniconda3\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (1.0.9)
Requirement already satisfied: idna in c:\Users\Ranjana\miniconda3\Lib\site-packages (from httpx<1,>=0.25.0->jupyterlab->jupyter) (3.11)
Requirement already satisfied: h11>=0.16 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from httpcore==1.*->httpx<1,>=0.25.0->jupyterlab->jupyter) (0.16.0)
Requirement already satisfied: argon2-cffi>=21.1 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (25.1.0)
Requirement already satisfied: jupyter-events>=0.11.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.12.1)
Requirement already satisfied: jupyter-server-terminals>=0.4.4 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.5.4)
Requirement already satisfied: nbformat>=5.3.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (5.10.4)
Requirement already satisfied: prometheus-client>=0.9 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.25.0)
Requirement already satisfied: pywinpty!=3.0.4,>=2.0.1 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (3.0.5)
Requirement already satisfied: send2trash>=1.8.2 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (2.1.0)
Requirement already satisfied: terminado>=0.8.3 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.18.1)
Requirement already satisfied: websocket-client>=1.7 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.9.0)
Requirement already satisfied: babel>=2.10 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.18.0)
Requirement already satisfied: json5>=0.9.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.15.0)
Requirement already satisfied: jsonschema>=4.18.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (4.26.0)
Requirement already satisfied: requests>=2.31 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.33.1)
Requirement already satisfied: argon2-cffi-bindings in c:\Users\Ranjana\miniconda3\Lib\site-packages (from argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (25.1.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jinja2>=3.0.3->jupyterlab->jupyter) (3.0.3)
Requirement already satisfied: attrs>=22.2.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (26.1.0)
Requirement already satisfied: jsonschema-specifications>=2023.03.6 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2025.9.1)
Requirement already satisfied: referencing>=0.28.4 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (0.37.0)
Requirement already satisfied: rpds-py>=0.25.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jsonschema>=4.18.0->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2026.5.1)
Requirement already satisfied: python-json-logger>=2.0.4 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (4.1.0)
Requirement already satisfied: pyyaml>=5.3 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (6.0.3)
Requirement already satisfied: rfc3339-validator in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.1.4)
Requirement already satisfied: rfc3986-validator>=0.1.1 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (0.1.1)
Requirement already satisfied: fqdn in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.5.1)
Requirement already satisfied: isoduration in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (20.11.0)
Requirement already satisfied: jsonpointer>1.13 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (3.1.1)
Requirement already satisfied: rfc3987-syntax>=1.1.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.1.0)
Requirement already satisfied: uri-template in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.3.0)
Requirement already satisfied: webcolors>=24.6.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (25.10.0)
Requirement already satisfied: beautifulsoup4 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from nbconvert->jupyter) (4.15.0)
Requirement already satisfied: bleach!=5.0.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (6.4.0)
Requirement already satisfied: defusedxml in c:\Users\Ranjana\miniconda3\Lib\site-packages (from nbconvert->jupyter) (0.7.1)
Requirement already satisfied: jupyterlab-pygments in c:\Users\Ranjana\miniconda3\Lib\site-packages (from nbconvert->jupyter) (0.3.0)
Requirement already satisfied: mistune<4,>=2.0.3 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from nbconvert->jupyter) (3.3.0)
Requirement already satisfied: nbclient>=0.5.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from nbconvert->jupyter) (0.11.0)
Requirement already satisfied: pandocfilters>=1.4.1 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from nbconvert->jupyter) (1.5.1)
Requirement already satisfied: webencodings in c:\Users\Ranjana\miniconda3\Lib\site-packages (from bleach!=5.0.0->bleach[css]!=5.0.0->nbconvert->jupyter) (0.5.1)
Requirement already satisfied: tinycss2>=1.1.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from bleach[css]!=5.0.0->nbconvert->jupyter) (1.5.1)
Requirement already satisfied: fastjsonschema>=2.15 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from nbformat>=5.3.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (2.21.2)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (3.4.4)
Requirement already satisfied: urllib3<3,>=1.26 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from requests>=2.31->jupyterlab-server<3,>=2.28.0->jupyterlab->jupyter) (2.6.3)
Requirement already satisfied: lark>=1.2.2 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from rfc3987-syntax>=1.1.0->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.3.1)
Requirement already satisfied: cffi>=1.0.1 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.17.1)
Requirement already satisfied: pycparser in c:\Users\Ranjana\miniconda3\Lib\site-packages (from cffi>=1.0.1->argon2-cffi-bindings->argon2-cffi>=21.1->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (3.0)
Requirement already satisfied: soupsieve>=1.6.1 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from beautifulsoup4->nbconvert->jupyter) (2.8.4)
Requirement already satisfied: arrow>=0.15.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from isoduration->jsonschema[format-nongpl]>=4.18.0->jupyter-events>=0.11.0->jupyter-server<3,>=2.19.0->jupyterlab->jupyter) (1.4.0)
Downloading psycopg-3.3.6-py3-none-any.whl (215 kB)
Downloading psycopg_binary-3.3.6-cp313-cp313-win_amd64.whl (3.7 MB)
   ---------------------------------------- 0.0/3.7 MB ? eta -:--:--
   ------------------------- -------------- 2.4/3.7 MB 11.8 MB/s eta 0:00:01
   ---------------------------------------- 3.7/3.7 MB 10.4 MB/s  0:00:00
Downloading jupyter-1.1.1-py2.py3-none-any.whl (2.7 kB)
Downloading jupyter_console-6.6.3-py3-none-any.whl (24 kB)
Installing collected packages: psycopg-binary, psycopg, jupyter-console, jupyter

   ---------------------------------------- 0/4 [psycopg-binary]
   ---------- ----------------------------- 1/4 [psycopg]
   ---------- ----------------------------- 1/4 [psycopg]
   ---------- ----------------------------- 1/4 [psycopg]
   ---------- ----------------------------- 1/4 [psycopg]
   ---------- ----------------------------- 1/4 [psycopg]
   -------------------- ------------------- 2/4 [jupyter-console]
   ---------------------------------------- 4/4 [jupyter]

Successfully installed jupyter-1.1.1 jupyter-console-6.6.3 psycopg-3.3.6 psycopg-binary-3.3.6
Note: you may need to restart the kernel to use updated packages.

  WARNING: The script jupyter-console.exe is installed in 'c:\Users\Ranjana\miniconda3\Scripts' which is not on PATH.
  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.

In [4]:
%pip install sqlalchemy

Collecting sqlalchemy
  Downloading sqlalchemy-2.1.4-cp313-cp313-win_amd64.whl.metadata (9.9 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\Users\Ranjana\miniconda3\Lib\site-packages (from sqlalchemy) (4.15.0)
Downloading sqlalchemy-2.1.4-cp313-cp313-win_amd64.whl (2.4 MB)
   ---------------------------------------- 0.0/2.4 MB ? eta -:--:--
   ------------------------- -------------- 1.6/2.4 MB 9.9 MB/s eta 0:00:01
   ---------------------------------------- 2.4/2.4 MB 8.9 MB/s  0:00:00
Installing collected packages: sqlalchemy
Successfully installed sqlalchemy-2.1.4
Note: you may need to restart the kernel to use updated packages.

In [3]:
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)
print("Scikit-learn:", sklearn.__version__)
print("TensorFlow:", tf.__version__)

Pandas: 3.0.3
NumPy: 2.4.6
Scikit-learn: 1.9.0
TensorFlow: 2.21.0

In [5]:
DATA_DIR = Path("../data/raw")
csv_path = DATA_DIR / "diabetic_data.csv"

In [6]:
df = pd.read_csv(
    csv_path,
    dtype=str,
    keep_default_na=False
)

In [7]:
print("Dataset shape:", df.shape)
print("\nColumn names:")
print(df.columns.tolist())

Dataset shape: (101766, 50)

Column names:
['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight', 'admission_type_id', 'discharge_disposition_id', 'admission_source_id', 'time_in_hospital', 'payer_code', 'medical_specialty', 'num_lab_procedures', 'num_procedures', 'num_medications', 'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1', 'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult', 'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide', 'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide', 'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone', 'tolazamide', 'examide', 'citoglipton', 'insulin', 'glyburide-metformin', 'glipizide-metformin', 'glimepiride-pioglitazone', 'metformin-rosiglitazone', 'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted']

In [8]:
print("\nFirst five rows:")
display(df.head())

First five rows:

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [9]:
print("\nData types:")
print(df.dtypes)

Data types:
encounter_id                str
patient_nbr                 str
race                        str
gender                      str
age                         str
weight                      str
admission_type_id           str
discharge_disposition_id    str
admission_source_id         str
time_in_hospital            str
payer_code                  str
medical_specialty           str
num_lab_procedures          str
num_procedures              str
num_medications             str
number_outpatient           str
number_emergency            str
number_inpatient            str
diag_1                      str
diag_2                      str
diag_3                      str
number_diagnoses            str
max_glu_serum               str
A1Cresult                   str
metformin                   str
repaglinide                 str
nateglinide                 str
chlorpropamide              str
glimepiride                 str
acetohexamide               str
glipizide                   str
glyburide                   str
tolbutamide                 str
pioglitazone                str
rosiglitazone               str
acarbose                    str
miglitol                    str
troglitazone                str
tolazamide                  str
examide                     str
citoglipton                 str
insulin                     str
glyburide-metformin         str
glipizide-metformin         str
glimepiride-pioglitazone    str
metformin-rosiglitazone     str
metformin-pioglitazone      str
change                      str
diabetesMed                 str
readmitted                  str
dtype: object

In [10]:
print("\nReadmission labels:")
print(df["readmitted"].value_counts(dropna=False))

Readmission labels:
readmitted
NO     54864
>30    35545
<30    11357
Name: count, dtype: int64

Load the cohort in Python and verify it

In [11]:

cohort_path = Path(
    "../data/processed/readmission_cohort.csv"
)

cohort = pd.read_csv(cohort_path)

In [12]:
print("Cohort shape:", cohort.shape)
print("\nColumns:")
print(cohort.columns.tolist())

print("\nTarget distribution:")
print(
    cohort["readmitted_within_30_days"]
    .value_counts(dropna=False)
)

print("\nTarget proportions:")
print(
    cohort["readmitted_within_30_days"]
    .value_counts(normalize=True, dropna=False)
)

print("\nDuplicate encounter IDs:",
      cohort["encounter_id"].duplicated().sum())

display(cohort.head())

Cohort shape: (101766, 23)

Columns:
['encounter_id', 'patient_nbr', 'admission_type_id', 'discharge_disposition_id', 'admission_source_id', 'time_in_hospital', 'num_lab_procedures', 'num_procedures', 'num_medications', 'number_outpatient', 'number_emergency', 'number_inpatient', 'number_diagnoses', 'max_glu_serum', 'a1cresult', 'diag_1', 'diag_2', 'diag_3', 'readmitted', 'race', 'gender', 'age', 'readmitted_within_30_days']

Target distribution:
readmitted_within_30_days
0    90409
1    11357
Name: count, dtype: int64

Target proportions:
readmitted_within_30_days
0    0.888401
1    0.111599
Name: proportion, dtype: float64

Duplicate encounter IDs: 0

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,...,max_glu_serum,a1cresult,diag_1,diag_2,diag_3,readmitted,race,gender,age,readmitted_within_30_days
0,2278392,8222157,6,25,1,1,41,0,1,0,...,NaN,NaN,250.83,NaN,NaN,NO,Caucasian,Female,[0-10),0
1,149190,55629189,1,1,7,3,59,0,18,0,...,NaN,NaN,276,250.01,255,>30,Caucasian,Female,[10-20),0
2,64410,86047875,1,1,7,2,11,5,13,2,...,NaN,NaN,648,250,V27,NO,AfricanAmerican,Female,[20-30),0
3,500364,82442376,1,1,7,2,44,1,16,0,...,NaN,NaN,8,250.43,403,NO,Caucasian,Male,[30-40),0
4,16680,42519267,1,1,7,1,51,0,8,0,...,NaN,NaN,197,157,250,NO,Caucasian,Male,[40-50),0

In [16]:
print("Pandas:", pd.__version__)
print("Scikit-learn:", sklearn.__version__)
print("SQLAlchemy:", sqlalchemy.__version__)
print("PostgreSQL driver: installed")

Pandas: 3.0.3
Scikit-learn: 1.9.0
SQLAlchemy: 2.1.4
PostgreSQL driver: installed

In [ ]:
from sqlalchemy import create_engine, text
from sqlalchemy.engine import URL  # <-- Import URL helper
from getpass import getpass

db_password = getpass("PostgreSQL password: ")

# Safely builds the URI and automatically escapes special characters
connection_url = URL.create(
    drivername="postgresql+psycopg",
    username="postgres",
    password=db_password,
    host="localhost",
    port=5432,
    database="healthcare_readmission"
)

engine = create_engine(connection_url)

with engine.connect() as conn:
    print(conn.execute(text("SELECT version()")).scalar())